# Generated by Django 4.1.5 on 2023-01-27 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor_Name', models.CharField(max_length=50)),
                ('Doctor_Specialization', models.CharField(max_length=50)),
                ('Doctor_Contact_Number', models.IntegerField()),
                ('Doctor_Location', models.CharField(max_length=50)),
                ('Entered_by', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='create_employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_Firstname', models.CharField(max_length=50)),
                ('Employee_Lastname', models.CharField(max_length=50)),
                ('Employee_Email', models.EmailField(max_length=254)),
                ('Employee_Password', models.CharField(max_length=100)),
                ('Employee_Date_of_Joining', models.DateTimeField(auto_now_add=True)),
                ('Employee_Status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='doctor_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor_Name', models.CharField(max_length=50)),
                ('Date_of_Schedule', models.DateField()),
                ('Time_of_Schedule', models.TimeField()),
                ('Entered_by', models.CharField(max_length=50)),
                ('Doctor_Schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.add_doctor')),
            ],
        ),
        migrations.CreateModel(
            name='deals_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor_Name', models.CharField(max_length=50)),
                ('Product_Name', models.CharField(max_length=50)),
                ('Quantity_Ordered', models.IntegerField()),
                ('Entered_by', models.CharField(max_length=50)),
                ('Doctor_Deals_Detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.add_doctor')),
                ('Product_Deals_Detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.add_product')),
            ],
        ),
        migrations.AddField(
            model_name='add_doctor',
            name='Doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.create_employee'),
        ),
        migrations.AddField(
            model_name='add_product',
            name='Product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Employee.create_employee'),
            preserve_default=False,
        ),
    ]
