# Generated by Django 4.1.5 on 2023-01-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_add_doctor_create_employee_doctor_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_doctor',
            name='Doctor_Contact_Number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='create_employee',
            name='Employee_Email',
            field=models.EmailField(max_length=25),
        ),
        migrations.AlterField(
            model_name='create_employee',
            name='Employee_Password',
            field=models.CharField(max_length=10),
        ),
    ]
